site_name: Marvel Champions - Guide de Référence v1.7 
site_url: https://deejimy.github.io/mc-reference/


theme:
    name: 'material'
    language: 'fr'
    logo: img/icons8-marvel.svg
    favicon: img/icons8-marvel-16.png
    palette:
      scheme: default
      primary: red
      accent: black
    features:
    - navigation.footer 
    
# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - roamlinks 